use_frameworks!

target 'TinderSwipeView_Example' do

  pod 'TinderSwipeView', :path => '/Users/saish98/Documents/GitHub/TinderSwipeView-Saish'
#  pod 'TinderSwipeView', :git => 'https://github.com/saish98/TinderSwipeView.git', :branch => 'saish98/ui-changes'
end
